#!/bin/sh
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr1.m > genosum_chr1.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr2.m > genosum_chr2.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr3.m > genosum_chr3.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr4.m > genosum_chr4.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr5.m > genosum_chr5.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr6.m > genosum_chr6.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr7.m > genosum_chr7.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr8.m > genosum_chr8.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr9.m > genosum_chr9.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr10.m > genosum_chr10.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr11.m > genosum_chr11.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr12.m > genosum_chr12.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr13.m > genosum_chr13.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr14.m > genosum_chr14.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr15.m > genosum_chr15.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr16.m > genosum_chr16.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr17.m > genosum_chr17.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr18.m > genosum_chr18.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr19.m > genosum_chr19.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr20.m > genosum_chr20.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr21.m > genosum_chr21.log &
nohup matlab -nodisplay -nodesktop -nosplash < genosum_chr22.m > genosum_chr22.log &
