#!/bin/bash
gene_pos_file=$1
gexp_file=$2
snps_maf_file=$3
snps_map_file=$4
alpha=$5
upstream=$6
downstream=$7
nperms=$8

##Find cis-SNPs
#$SIGNET_SCRIPT_ROOT/cis-eQTL/cis-SNPs.sh $upstream $downstream 

# Cis-eQTL Analysis
wait
$SIGNET_SCRIPT_ROOT/cis-eQTL/common.ciseQTL.sh $alpha
exit
$SIGNET_SCRIPT_ROOT/cis-eQTL/low.ciseQTL.sh $alpha $nperms
$SIGNET_SCRIPT_ROOT/cis-eQTL/all.ciseQTL.sh $alpha
wait

echo -e 'Cis-eQTL analysis completed!\n'
